<?xml version="1.0" encoding="UTF-8"?>
<!-- NetBeans Platform build script for SmartHomeProject -->
<project name="SmartHomeProject" default="default" basedir=".">
    <description>Builds, tests, and runs the project SmartHomeProject.</description>
    <import file="nbproject/build-impl.xml"/>
</project>
